import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Container, Nav, Navbar, NavbarBrand, NavbarCollapse, NavbarToggle } from "react-bootstrap";
import Link from "next/link";
import TanstackProvider from "./tanstackProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        
      >
        <TanstackProvider>
          <Navbar expand="sm" className="bg-body-tertiary">
            <Container>
              <NavbarBrand>Resturanteur</NavbarBrand>
              <NavbarToggle aria-controls="basic-navbar-nav" />
              <NavbarCollapse>
                <Nav className="me-auto">
                    <Link href={"/"} className="text-black nav-link">
                      Home
                    </Link>
                    <Link href={"/login"} className="text-black nav-link">
                      login
                    </Link>
                </Nav>
              </NavbarCollapse>
            </Container>
          </Navbar>
          {children}
        </TanstackProvider>
      </body>
    </html>
  );
}
